### ISSUE TITLE
Forgot your Password Error

### ISSUE THREAD

**Issue by aromanhxm** [openkm/document-management-system#73]
al intentar restablecer una contraseña de cualquier cuenta por medio de la Opcion Forgot your Password
me da el error "Failed reset the user password"
mismo error con una cuenta con rol de ADMIN, que una cuenta con rol de USER.

la instalada es  Version: 6.3.6 (build: 87d181f)

revisando el log $TOMCAT_HOME\log\openkm.log

encuentro el siguiente error:

2018-06-13 18:49:58,719 [ajp-nio-127.0.0.1-8109-exec-7] [] **ERROR c.o.servlet.PasswordResetServlet - You need administrator grants for this change
com.openkm.core.AccessDeniedException: You need administrator grants for this change**
at com.openkm.dao.AuthDAO.checkAccessGrants(AuthDAO.java:599) ~[classes/:6.3.6]
at com.openkm.dao.AuthDAO.updateUserPassword(AuthDAO.java:142) ~[classes/:6.3.6]
at com.openkm.servlet.PasswordResetServlet.doPost(PasswordResetServlet.java:71) ~[classes/:6.3.6]
at javax.servlet.http.HttpServlet.service(HttpServlet.java:661) [servlet-api.jar:na]
at javax.servlet.http.HttpServlet.service(HttpServlet.java:742) [servlet-api.jar:na]
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231) [catalina.jar:8.5.24]
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [catalina.jar:8.5.24]
at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52) [tomcat-websocket.jar:8.5.24]
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [catalina.jar:8.5.24]
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [catalina.jar:8.5.24]

Saludos

**Comment by gnujavasergio** [comment]
@darkman97i  ya se resolvio el error de resetear la contraseña y se arreglo la interfaz no tenia ningun diseño dejo una captura de como quedo la interfaz.

![seleccion_161](https://user-images.githubusercontent.com/654790/41636876-f24772f4-741e-11e8-845a-0cfce51bbec2.png)

@aromanhxm con el pull request realizo ya tendras el problema solucionado

Saludos
